name: FastAPI CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.10"

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Debug Config
    run: |
      python -c "from app.config import MONGO_URI, DATABASE_NAME, COLLECTION_NAME; print('MONGO_URI =', MONGO_URI); print('DATABASE_NAME =', DATABASE_NAME); print('COLLECTION_NAME =', COLLECTION_NAME)"

  - name: Run Tests
    run: |
      python -m pytest